### PR TITLE
[DRAFT] rough idea for Leap icon

### PR DESCRIPTION
**Pull request by aspiers**
I really like [the Tumbleweed figure-of-8 icon](https://github.com/cyntss/opensuse-landing-page/blob/master/assets/images/tumbleweed-icon.png).  The [regular release icon](https://github.com/cyntss/opensuse-landing-page/blob/master/assets/images/opensuse-regular-release-icon.svg) also looks nice, although IMHO it is slightly less obvious what it represents.  I had a quick think about the core differences between Leap and Tumbleweed, and had an idea for an icon which is visually similar to the Tumbleweed icon but also communicates the regular release cycle of Leap, and incorporates the motion of leaping ;-)

I've never used Inkscape before and I'm not a designer, but hopefully this is good enough to communicate my idea of an icon for Leap.

You can see how this looks in context here: http://aspiers.github.io/opensuse-landing-page/

### CODE REVIEW

**Comment by sysrich** [comment]
ooh..hmm..I like both the old Leap icon and your suggested one..

a lot

The only thing I will say as a thought is the current Leap icon is intended to be clearly more 'solid' than Tumbleweed, hence it's angular nature. It's trying to represent something to the user "this is a box you can rely on"

It's thin layer with the thicker square on top is representing Leaps SLE + openSUSE nature

Your icon eschews those attempts to carry something to the user for a representation of Leap's development model, which might have interest to developers, but is arguably less communicative about what Leap is trying to be to users.

**Comment by aspiers** [comment]
Yeah I agree with everything you say here.  And again, I do visually like the existing one.  However it wasn't obvious to me that the two layers represent SLE / openSUSE.  That's a really nice idea but I'm worried the icon is perhaps somehow slightly too generic at this point, and even more so that it doesn't really connect with the name "Leap" (to me anyway).  I've said my piece, now I should probably leave it to the design experts :-)  @cyntss, @kwwii, what do you think?

**Comment by aspiers** [comment]
A couple more thoughts here.

1. I wonder is there any way to combine the two ideas into a single icon?
2. All this stuff is highly subjective, so maybe rather than an individual or small group of people deciding, poll the whole community?  That's more the F/OSS way to decide anyway, and it's how "Leap" originated, right? :-)

**Comment by sysrich** [comment]
1. Good idea - no idea how from me

2. On the idea of pulling more people in - sure, ask anyone you know who you think can provide useful feedback

On involving everyone - No, I'm sorry, I know there are some people that believe open source must be done using broad democratic principles, but wide debates will never produce clear decisions - just look at the current debate on 32-bit support on Leap, past debates about systemd, wayland, or every single openSUSE-branding package ever (and I should know..as it's long suffering maintainer)

I would argue the truer F/OSS way is 'those who do decide' - and as long as we're transparent, and open to anyone and everyone who wants to contribute their thoughts on the topic, and thinking with a broader audience in mind, we can hopefully put something together that works, that most people also like

**Comment by aspiers** [comment]
OK I've updated it to combine the ideas.  Doesn't look as beautiful as the dots, but with some TLC from real designers I'm sure that could be fixed - what do you think?

**Comment by aspiers** [comment]
> I would argue the truer F/OSS way is 'those who do decide' - and as long as we're transparent, and open to anyone and everyone who wants to contribute their thoughts on the topic, and thinking with a broader audience in mind, we can hopefully put something together that works, that most people also like

Agreed!  I think we were saying the same thing - I guess I was suggesting to make this process of discussing the logo more transparent and open by mentioning it on the mailing lists.

**Comment by ddemaio** [comment]
Hi guys,
We have a few other icons that were proposed. Unfortunately this is all coming a little late. I had to order the tshirts last week to get them in time for the release. I also had to order some that are going stateside with that logo as well. I like your logo @aspiers I think we can improve upon the one I put on the tshirt, but I think we should stick with the original logo and transition to the new logo after the new year. Thoughts
leap_logos

**Comment by aspiers** [comment]
Whoa, these are great!  Here's my take:

Numbers 1 and 5 are similar but I prefer 5 because it implies that every release is better (higher) than the last.  Number 2 is in some ways the most aesthetically pleasing to me, but IMHO too similar to the Mozilla 'fire' fox.  Number 3 is also awesome but to my (zoologically challenged) eye looks more like a frog than a geeko.  Number 4 nicely captures the multiple layers of Leap (SLE+openSUSE) but the periodic release element seems missing.

In summary, they all have awesome characteristics, but for me none of them are quite perfect yet (and certainly my suggestions aren't either).  It would be so cool if we could find a logo which encapsulates all of the following elements without becoming too busy or over-complicated:

1. some representation of periodic stable releases (i.e. more than one iteration)
2. a leaping motion from bottom left to top right
3. two layers (SLE+openSUSE)
4. one or more geekos ;-)

but it's far beyond my skills to do that.

> I think we should stick with the original logo and transition to the new logo after the new year.

No objections here but I'll stay out of that decision and leave it to you guys - I haven't been involved enough in Leap or know enough about it to deserve a vote :)

**Comment by ddemaio** [comment]
@aspiers thank you. I Agree # 5. I had the same outlook. I think we could go forward and develop it further going along. The page is mostly about progressing and then further progressing it, which is the same thing with the search page. Obviously DuckDuckGo can be included on that and a few other. It's all small steps forward.

**Comment by sysrich** [comment]
I dont like #5 because it has a 'up and down' aspect to it.. like it's going forward and backwards or something

But I might be reading too much into it..

**Comment by aspiers** [comment]
BTW I just added a fifth item to [my shopping list above](https://github.com/cyntss/opensuse-landing-page/pull/37#issuecomment-138930264).

**Comment by cyntss** [comment]
I like your logo Adam.. but... instantly reminded me of some cheap food... lol 
image

**Comment by aspiers** [comment]
LOL! Yeah that occurred to me too ... :-/  I was hoping someone with real design skills (not me) might be able to take the general idea and make it look good ... and not like fast food ;-)

**Comment by cyntss** [comment]
haha Adam you did much better than some people that study graphic design for 5 years! lol

**Comment by cyntss** [comment]
@sysrich I think we should close this PR for now since we have tshirts and other materials with the current logo, is that okay with you?

**Comment by aspiers** [comment]
Haha wow thanks! Maybe I'll give up coding and become a designer ... maybe not, I think I just got lucky this time ;-)

I'm happy if this is closed but hopefully my thoughts and ideas can be taken into account if the logo is changed in the future.

**Comment by sysrich** [comment]
OK with me

**Pull request closed without merging**
