### PR TITLE
Use navigator language as default if available

### PR DESCRIPTION
**Pull request by super7ramp**
It will try to use navigator.language if no cookieLanguage is set.
If the navigator language is not available, falling back to English.

### CODE REVIEW

**Comment by cyntss** [comment]
I tested it and seems to work well :)

Now, there is a little issue I see. Since we dont have all of the different translations for when a language comes from different countries, e.g.: en-US, en-EN, es-ES, es-AR, es-CL, etc etc etc... what if we only read the first 2 characters of the language name (when no match was found with the complete name), which will be the general language name that we are more likely to have translated?

**Comment by super7ramp** [comment]
A second commit that do what you described.
Maybe it would be good to try the languages in the navigator.languages array too...

**Comment by cyntss** [comment]
What do you mean with trying the languages in the navigator.language array? as far as I know, the property language of the object navigator saves a string not an array.

**Comment by super7ramp** [comment]
Sorry, what I said wasn't clear: There is navigator.language which is a string and also navigator.language**s** which is an array of strings. The former contains the preferred language and the latter contains several preferred languages (sorted by preference). But I am not sure all browsers have this property.

**Comment by cyntss** [comment]
Oh ok, I never heard of navigator.languages.
According to this document it is only compatible with Chrome and Firefox:
https://localizejs.com/questions/integrating/detect-languages

Important note: "We don't recommend relying on this method due to its lack of cross-browser support."

I would drop this option for now.

**Comment by cyntss** [comment]
So, for now I think your commit does the work and is ready to be merged, unless you want to do some other work on top, I will merge it. Awaiting for your confirmation.

**Comment by super7ramp** [comment]
OK, go ahead :)

**Comment by super7ramp** [comment]
Thanks!

**Comment by coolo** [comment]
can this be transferred to the searchPage repo too? there we have the same problem

**Pull request merged**
