### PR TITLE
Improved improvements from adam and richard

### PR DESCRIPTION
**Pull request by sysrich**
my proposed change set, incorporating feedback from #34

### CODE REVIEW

**Comment by aspiers** [comment]
Can you push this to your `gh-pages` so we can preview it?  And why doesn't github let us preview any damn branch we want? :-/

**Comment by sysrich** [comment]
I already have

**Comment by sysrich** [comment]
http://sysrich.github.io/opensuse-landing-page/

The leap section needs love (missing install button and the link to the portal)

And the news section needs the HR removed

Cynthia said she could do it.

**Comment by aspiers** [comment]
I still think Leap should be on the left.  IMHO @cornelius [hit the nail on the head](https://github.com/cyntss/opensuse-landing-page/pull/34#issuecomment-138957126) regarding respecting the majority of the existing user base.  But if you still disagree and want to overrule us (which is of course your prerogative), it would be nicer simply to drop the patch which swaps them, rather than pollute history and the PR with two commits which simply annul each other.

**Comment by cyntss** [comment]
@aspiers Sorry I didnt read the hole thread in the other discussion but what I understood (just from the commit name in Swap leap and Tumbleweed which I quote "More people will be interested in the stable release, so put Leap on the left and Tumbleweed on the right.") I have to disagree with you.

In a website, the most Positive side of the screen is the Right side, not the Left, being the reason why most ads are located on the right of a webpage. Because we read from left to right, we always end up paying sightly more attention to the Right; of course, for Arabic speaking countries this might not be the case. That being said, It is not like I disagree with you on the idea of focusing more on Leap over Tumbleweed, but the positioning on screen.

So, unless @sysrich wants to change it, I think the current layout is the proper one for our user base.

**Comment by sysrich** [comment]
You're the professional - I don't want to change it.. closing this PR

I guess we take everything from #34 and then remove Machinery and fix the News HR?

**Comment by cyntss** [comment]
@sysrich hmm I think this PR was the right one lol. #34 has the wrong position for Leap and Tumbleweed. I think you misunderstood me maybe

**Comment by cyntss** [comment]
Tomorrow I remove the line in News and add the Install button on Leap, and that should be it.

**Comment by sysrich** [comment]
oh, okay, basically, you're the boss, I've given my opinions, and at this point I'm equally happy if you take them, or don't :)

**Pull request merged**
